const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');

(async () => {
    const browser = await chromium.launch({ headless: true });
    try {
        const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        page.on('dialog', dialog => dialog.dismiss());
        await page.route('https://**/*', route => /tailwindcss|plotly|mathjs|xlsx/.test(route.request().url()) ? route.continue() : route.abort());
        await page.goto(pathToFileURL(path.resolve(__dirname, '../index.html')).href);
        await page.evaluate(() => switchSection('cartera'));
        assert.ok(await page.locator('#workspaceData').isVisible());
        await page.locator('[data-workspace-scope="aggregate"]').click();
        await page.locator('[data-workspace-step="diagnosis"]').click();
        assert.ok(await page.locator('#workspaceAggregate').isVisible());
        assert.equal(await page.locator('#portfolioSubtabContent-main').isVisible(), false);
        await page.locator('[data-workspace-scope="individual"]').click();
        const checks = await page.evaluate(() => {
            const weights = parseFundProposalInput('ES0000000001;1\nES0000000002;99').map(r => r.weight);
            const origin = { isin:'ES0000000001', name:'Fondo origen A EUR', category:'Bonos', score:9, ter:1, aum:100, ret5:4, risk5:6 };
            const records = Array.from({ length:300 }, (_, i) => ({ ...origin, isin:'ES'+String(i+2).padStart(10,'0'), name:'Candidato '+i, score:3 }));
            fundUniverseState = { records:[origin,...records], isinIndex:new Map([origin,...records].map(r=>[r.isin,r])) };
            approvedFundsState = { records:[{...origin,isin:'ES9999999999',name:'Fondo origen B USD'}], isinIndex:new Map() };
            const noDowngrade = getBetterFundRecommendations(origin).length === 0;
            const noApproval = !isFundApprovedRecord(origin);
            fundProposalState.rows = [{ isin:origin.isin,current:origin,proposed:origin,weight:100,recommendations:[],cheaperClasses:[] }];
            renderFundProposalPortfolio();
            const panel = document.getElementById('fundProposalFullUniverse-0');
            const bounded = panel.querySelectorAll('.fund-option').length;
            FundSelector.search('Candidato 299',panel.id);
            const found = panel.textContent.includes('Candidato 299');
            fundProposalState.rows[0].proposed = {...records[0],category:'Acciones'};
            const crossCategoryBlocked = Number.isNaN(fundProposalWeighted('score'));
            fundProposalState.rows[0].proposed = origin;
            return {weights,noDowngrade,noApproval,bounded,found,crossCategoryBlocked};
        });
        assert.deepEqual(checks.weights,[1,99]);
        assert.ok(checks.noDowngrade && checks.noApproval && checks.found && checks.crossCategoryBlocked);
        assert.ok(checks.bounded <= 40);
        await page.locator('[data-workspace-step="proposal"]').click();
        assert.ok(await page.locator('#workspaceProposal').isVisible());
        assert.equal(await page.locator('#portfolioSubtabContent-funds').isVisible(), false);
        const out = process.env.BROWSER_OUTPUT_DIR || path.resolve(__dirname,'../test-results');
        fs.mkdirSync(out,{recursive:true});
        await page.screenshot({path:path.join(out,'proposal-desktop.png'),fullPage:true});
        await page.evaluate(() => generateFundProposalReport());
        assert.ok(await page.locator('#workspaceIndividualReports').isVisible());
        assert.ok(await page.evaluate(() => PortfolioWorkspace.snapshots.proposal));
        await page.locator('#reportIncludeCharts').uncheck();
        await page.evaluate(() => generateFundProposalReport());
        assert.equal(await page.evaluate(() => new DOMParser().parseFromString(fundProposalState.reportHtml,'text/html').querySelectorAll('figure').length),0);
        await page.locator('#reportIncludeCharts').check();
        await page.evaluate(() => generateFundProposalReport());
        const printPage = await browser.newPage();
        await printPage.setContent(await page.evaluate(() => fundProposalState.reportHtml));
        await printPage.pdf({path:path.join(out,'proposal-report.pdf'),format:'A4',printBackground:true});
        await printPage.screenshot({path:path.join(out,'proposal-report.png'),fullPage:true});
        await printPage.close();
        const imported = await page.evaluate(async () => {
            const wb = XLSX.utils.book_new();
            XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([['ticker','weight'],['A',1],['B',99]]),'weights');
            const prices = [['date','A','B'], ...Array.from({length:60},(_,i)=>[new Date(Date.UTC(2024,0,1+i*7)),100+i,100+i/2])];
            XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(prices),'prices');
            document.getElementById('portfolioPricesInBase').checked = true;
            await importBacktestPortfolioWorkbook(wb,'fixture-semanal.xlsx');
            await portfolioAnalysisPromise;
            const result = {frequency:loadedPortfolio.frequency,weights:loadedPortfolio.entries.map(e=>e.weight),points:loadedPortfolio.portfolioData.length};
            document.getElementById('portfolioCostBps').value = '10';
            result.stale = portfolioHistoryStale();
            document.getElementById('portfolioCostBps').value = '0';
            return result;
        });
        assert.equal(imported.frequency,'W'); assert.deepEqual(imported.weights,[.01,.99]); assert.equal(imported.points,60); assert.ok(imported.stale);
        await page.evaluate(() => generatePortfolioReport());
        assert.ok(await page.evaluate(() => Boolean(portfolioReportHtml && PortfolioWorkspace.snapshots.individual)));
        await page.locator('[data-workspace-step="data"]').click();
        await page.setViewportSize({width:390,height:844});
        await page.screenshot({path:path.join(out,'data-mobile.png'),fullPage:true});
        assert.deepEqual(errors,[]);
        console.log(JSON.stringify({checks,imported,errors},null,2));
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
