const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const fs = require('node:fs');

(async () => {
    const browser = await chromium.launch({ headless: true });
    try {
        const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        page.on('dialog', dialog => dialog.dismiss());
        await page.route('https://**/*', route => /tailwindcss|plotly|mathjs|xlsx|pdfmake|font-awesome/.test(route.request().url()) ? route.continue() : route.abort());
        await page.goto(pathToFileURL(path.resolve(__dirname, '../index.html')).href);
        await page.evaluate(() => switchSection('cartera'));
        assert.ok(await page.locator('#workspaceData').isVisible());
        await page.locator('[data-workspace-scope="aggregate"]').click();
        await page.locator('[data-workspace-step="diagnosis"]').click();
        assert.ok(await page.locator('#workspaceAggregate').isVisible());
        assert.ok(await page.locator('[data-workspace-tool="massive"]').isVisible());
        assert.equal(await page.locator('[data-workspace-tool="screener"]').count(),0);
        assert.equal(await page.locator('[data-workspace-step="proposal"]').isVisible(),false);
        await page.evaluate(()=>{PortfolioWorkspace.step='proposal';portfolioWorkflowRefresh();});
        assert.equal(await page.evaluate(()=>PortfolioWorkspace.step),'diagnosis');
        assert.ok(await page.locator('#workspaceAggregate').isVisible());
        await page.locator('[data-workspace-scope="screener"]').click();
        assert.ok(await page.locator('#portfolioSubtabContent-screener').isVisible());
        assert.equal(await page.locator('#workspaceAggregate').isVisible(),false);
        assert.equal(await page.locator('[data-workspace-step="report"]').isVisible(),false);
        assert.equal(await page.locator('[data-workspace-scope="screener"]').getAttribute('aria-pressed'),'true');
        await page.locator('[data-workspace-step="data"]').click();
        assert.ok(await page.locator('#workspaceData').isVisible());
        assert.equal(await page.locator('#portfolioBuilder').isVisible(),false);
        await page.locator('[data-workspace-step="diagnosis"]').click();
        assert.ok(await page.locator('#portfolioSubtabContent-screener').isVisible());
        assert.equal(await page.locator('#portfolioSubtabContent-main').isVisible(), false);
        await page.locator('[data-workspace-scope="individual"]').click();
        await page.locator('[data-workspace-step="diagnosis"]').click();
        assert.equal(await page.locator('[data-workspace-tool="massive"]').isVisible(),false);
        await page.locator('[data-workspace-tool="scoring"]').click();
        assert.equal(await page.locator('[data-workspace-tool="scoring"]').getAttribute('aria-pressed'),'true');
        assert.equal(await page.locator('[data-workspace-step="proposal"]').isVisible(),false);
        assert.equal(await page.locator('button:has-text("Word")').count(),0);
        await page.locator('[data-workspace-scope="initial"]').click();
        const checks = await page.evaluate(() => {
            const weights = parseFundProposalInput('ES0000000001;1\nES0000000002;99').map(r => r.weight);
            const origin = { isin:'ES0000000001', name:'Fondo origen A EUR', category:'Bonos', score:9, ter:1, aum:100, ret5:4, risk5:6 };
            const records = Array.from({ length:300 }, (_, i) => ({ ...origin, isin:'ES'+String(i+2).padStart(10,'0'), name:'Candidato '+i, score:3 }));
            fundUniverseState = { records:[origin,...records], isinIndex:new Map([origin,...records].map(r=>[r.isin,r])) };
            approvedFundsState = { records:[{...origin,isin:'ES9999999999',name:'Fondo origen B USD'}], isinIndex:new Map() };
            const noDowngrade = getBetterFundRecommendations(origin).length === 0;
            const noApproval = !isFundApprovedRecord(origin);
            fundProposalState.rows = [{ isin:origin.isin,current:origin,proposed:origin,weight:100,recommendations:[],cheaperClasses:[] }];
            renderFundProposalPortfolio();
            const panel = document.getElementById('fundProposalFullUniverse-0');
            const bounded = panel.querySelectorAll('.fund-option').length;
            FundSelector.search('Candidato 299',panel.id);
            const found = panel.textContent.includes('Candidato 299');
            fundProposalState.rows[0].proposed = {...records[0],category:'Acciones'};
            const crossCategoryBlocked = Number.isNaN(fundProposalWeighted('score'));
            fundProposalState.rows[0].proposed = origin;
            return {weights,noDowngrade,noApproval,bounded,found,crossCategoryBlocked};
        });
        assert.deepEqual(checks.weights,[1,99]);
        assert.ok(checks.noDowngrade && checks.noApproval && checks.found && checks.crossCategoryBlocked);
        assert.ok(checks.bounded <= 40);
        await page.locator('[data-workspace-step="proposal"]').click();
        assert.ok(await page.locator('#workspaceProposal').isVisible());
        assert.equal(await page.locator('#portfolioSubtabContent-funds').isVisible(), false);
        const alignment = await page.evaluate(() => {
            const portfolio = ['2024-01-31','2024-02-29','2024-03-31'].map((date,i)=>({date:new Date(date),price:100+i*10}));
            const bench = ['2024-01-30','2024-02-28','2024-03-28'].map((date,i)=>({date:new Date(date),price:200+i*10}));
            const aligned=alignPortfolioWithBenchmark(portfolio,bench);
            renderFundCategoryPie([{record:{category:'Renta fija'},weight:15},{record:{category:' renta  FIJA '},weight:15},{record:{category:'Acciones'},weight:70}]);
            const chart=document.getElementById('fundCategoryPieChart').data[0];
            return {points:aligned.x.length,first:aligned.benchmark[0],last:aligned.portfolio.at(-1),labels:chart.labels,weights:chart.values,disjoint:alignPortfolioWithBenchmark(portfolio,bench.map(p=>({...p,date:new Date('2020-01-01')})))};
        });
        assert.equal(alignment.points,3); assert.equal(alignment.first,100); assert.equal(alignment.last,120); assert.equal(alignment.disjoint,null);
        assert.deepEqual(alignment.weights,[30,70]);
        await page.evaluate(() => {
            fundProposalState.rows[0].weight=70;
            fundProposalState.rows.push({isin:'ES9999999998',weight:30,current:null,proposed:null,missing:true,recommendations:[],cheaperClasses:[]});
            renderFundProposalPortfolio();
        });
        await page.locator('#fundProposalTableBody button:has-text("Definir origen")').click();
        await page.locator('#initialOriginName').fill('Fondo cliente Adhoc');
        await page.locator('dialog .fund-selector-trigger').click();
        await page.locator('dialog input[type="search"]').fill('Fondo origen');
        await page.locator('dialog .fund-option').first().click();
        await page.locator('dialog button[type="submit"]').click();
        const proxy=await page.evaluate(()=>fundProposalState.rows[1].current);
        assert.equal(proxy.name,'Fondo cliente Adhoc'); assert.equal(proxy.isin,'ES9999999998'); assert.equal(proxy.originSource.proxyIsin,'ES0000000001'); assert.equal(proxy.ter,1);
        await page.evaluate(()=>generateFundProposalReport());
        assert.ok(await page.evaluate(()=>fundProposalState.reportHtml.includes('metricas estimadas con el proxy')));
        await page.locator('[data-workspace-step="proposal"]').click();
        await page.locator('#fundProposalTableBody button:has-text("Editar origen")').click();
        await page.locator('#initialOriginMode').selectOption('manual');
        await page.locator('#initialOriginName').fill('Fondo cliente manual');
        await page.locator('#initialMetric-ter').fill('2.25');
        await page.locator('#initialMetric-score').fill('5');
        await page.locator('dialog button[type="submit"]').click();
        const manual = await page.evaluate(() => {
            document.getElementById('fundProposalPortfolioInput').value='ES0000000001;70\nES9999999998;30';
            analyzeFundProposalPortfolio();
            return fundProposalState.rows[1].current;
        });
        assert.equal(manual.ter,2.25); assert.equal(manual.originSource.mode,'manual'); assert.equal(manual.name,'Fondo cliente manual');
        const out = process.env.BROWSER_OUTPUT_DIR || path.resolve(__dirname,'../test-results');
        fs.mkdirSync(out,{recursive:true});
        await page.locator('[data-workspace-scope="screener"]').click();
        await page.screenshot({path:path.join(out,'screener-desktop.png')});
        await page.setViewportSize({width:390,height:844});
        await page.screenshot({path:path.join(out,'screener-mobile.png')});
        await page.setViewportSize({width:1440,height:1000});
        await page.locator('[data-workspace-scope="initial"]').click();
        await page.locator('[data-workspace-step="proposal"]').click();
        await page.screenshot({path:path.join(out,'proposal-desktop.png'),fullPage:true});
        await page.evaluate(() => generateFundProposalReport());
        assert.ok(await page.locator('#workspaceInitialReports').isVisible());
        assert.ok(await page.evaluate(() => PortfolioWorkspace.snapshots.proposal));
        await page.locator('#reportIncludeCharts').uncheck();
        await page.evaluate(() => generateFundProposalReport());
        assert.equal(await page.evaluate(() => new DOMParser().parseFromString(fundProposalState.reportHtml,'text/html').querySelectorAll('figure').length),0);
        await page.locator('#reportIncludeCharts').check();
        await page.evaluate(() => generateFundProposalReport());
        const printPage = await browser.newPage();
        await printPage.setContent(await page.evaluate(() => fundProposalState.reportHtml));
        await printPage.pdf({path:path.join(out,'proposal-report.pdf'),format:'A4',printBackground:true});
        await printPage.screenshot({path:path.join(out,'proposal-report.png'),fullPage:true});
        await printPage.close();
        const downloadEvent = page.waitForEvent('download',{timeout:90000});
        const downloaded = await page.evaluate(() => ReportDesign.downloadPdf(fundProposalState.reportHtml,'test-initial.pdf'));
        assert.ok(downloaded);
        await (await downloadEvent).saveAs(path.join(out,'direct-download.pdf'));
        const imported = await page.evaluate(async () => {
            const wb = XLSX.utils.book_new();
            XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet([['ticker','weight'],['A',1],['B',99]]),'weights');
            const prices = [['date','A','B'], ...Array.from({length:60},(_,i)=>[new Date(Date.UTC(2024,0,1+i*7)),100+i,100+i/2])];
            XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(prices),'prices');
            document.getElementById('portfolioPricesInBase').checked = true;
            await importBacktestPortfolioWorkbook(wb,'fixture-semanal.xlsx');
            await portfolioAnalysisPromise;
            const result = {frequency:loadedPortfolio.frequency,weights:loadedPortfolio.entries.map(e=>e.weight),points:loadedPortfolio.portfolioData.length};
            document.getElementById('portfolioCostBps').value = '10';
            result.stale = portfolioHistoryStale();
            document.getElementById('portfolioCostBps').value = '0';
            return result;
        });
        assert.equal(imported.frequency,'W'); assert.deepEqual(imported.weights,[.01,.99]); assert.equal(imported.points,60); assert.ok(imported.stale);
        await page.evaluate(() => generatePortfolioReport());
        assert.ok(await page.evaluate(() => Boolean(portfolioReportHtml && PortfolioWorkspace.snapshots.individual)));
        assert.equal(await page.evaluate(()=>PortfolioWorkspace.snapshots.individual.proposal.length),0);
        const individualDownload = page.waitForEvent('download',{timeout:90000});
        await page.evaluate(()=>downloadPortfolioReportPdf());
        await (await individualDownload).saveAs(path.join(out,'individual-download.pdf'));
        await page.evaluate(()=>{
            const record=fundUniverseState.records[0];
            aggregatePositionsState=aggregateFundPositions([{isin:record.isin,name:record.name,amount:100000,account:'Cliente de prueba'}],'fixture-agregado.xlsx');
            aggregateScoringResults=aggregatePositionsState.aggregated.map(position=>createAggregateResultState(position,{record,status:'exact-isin'},{record:null,status:'not-approved'}));
        });
        const aggregateDownload = page.waitForEvent('download',{timeout:90000});
        await page.evaluate(()=>downloadManagerReportPdf());
        await (await aggregateDownload).saveAs(path.join(out,'aggregate-download.pdf'));
        await page.locator('[data-workspace-scope="initial"]').click();
        await page.locator('[data-workspace-step="proposal"]').click();
        await page.evaluate(()=>{
            window.testUniverse=fundUniverseState; fundUniverseState=null;
            document.getElementById('fundProposalPortfolioInput').value='ES9999999997;100'; analyzeFundProposalPortfolio();
        });
        await page.locator('#fundProposalTableBody button:has-text("Definir origen")').click();
        await page.locator('#initialOriginMode').selectOption('manual');
        await page.locator('#initialOriginName').fill('Origen manual sin universo');
        await page.locator('#initialOriginCategory').fill('Renta fija');
        await page.locator('#initialMetric-score').fill('5');
        await page.locator('#initialMetric-ter').fill('1.5');
        await page.locator('dialog button[type="submit"]').click();
        await page.evaluate(()=>generateFundProposalReport());
        assert.ok(await page.evaluate(()=>fundProposalState.reportHtml.includes('Origen manual sin universo')));
        assert.ok(await page.evaluate(()=>Number.isNaN(fundProposalState.rows[0].current.risk5)));
        await page.evaluate(()=>{fundUniverseState=window.testUniverse;delete window.testUniverse;});
        await page.locator('[data-workspace-scope="individual"]').click();
        await page.locator('[data-workspace-step="data"]').click();
        await page.setViewportSize({width:390,height:844});
        await page.screenshot({path:path.join(out,'data-mobile.png'),fullPage:true});
        assert.deepEqual(errors,[]);
        console.log(JSON.stringify({checks,alignment,proxy:proxy.originSource,manual:manual.originSource,imported,errors},null,2));
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
